name: Auto Update Matches
on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - src: actions/setup-python@v4
        with: { python-version: '3.10' }
      - run: pip install -r requirements.txt
      - run: python fetch_group_a.py # Group B mein fetch_group_b.py karein
      - run: |
          git config --global user.name "DarTeve-Bot"
          git add .
          git commit -m "Auto Update" || exit 0
          git push
